# Generated by Django 6.0.6 on 2026-07-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=63)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'register_employee',
            },
        ),
        migrations.CreateModel(
            name='company_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=63, unique=True)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_register',
            },
        ),
    ]
