# Generated by Django 6.0.6 on 2026-07-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_company_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_employee',
            name='role',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
